// Generated by gencpp from file haptic_base/PWMValues16.msg
// DO NOT EDIT!


#ifndef HAPTIC_BASE_MESSAGE_PWMVALUES16_H
#define HAPTIC_BASE_MESSAGE_PWMVALUES16_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace haptic_base
{
template <class ContainerAllocator>
struct PWMValues16_
{
  typedef PWMValues16_<ContainerAllocator> Type;

  PWMValues16_()
    : pwm_values()  {
      pwm_values.assign(0);
  }
  PWMValues16_(const ContainerAllocator& _alloc)
    : pwm_values()  {
  (void)_alloc;
      pwm_values.assign(0);
  }



   typedef boost::array<int16_t, 16>  _pwm_values_type;
  _pwm_values_type pwm_values;




  typedef boost::shared_ptr< ::haptic_base::PWMValues16_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haptic_base::PWMValues16_<ContainerAllocator> const> ConstPtr;

}; // struct PWMValues16_

typedef ::haptic_base::PWMValues16_<std::allocator<void> > PWMValues16;

typedef boost::shared_ptr< ::haptic_base::PWMValues16 > PWMValues16Ptr;
typedef boost::shared_ptr< ::haptic_base::PWMValues16 const> PWMValues16ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haptic_base::PWMValues16_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haptic_base::PWMValues16_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haptic_base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'haptic_base': ['/home/raven/ros_ws/src/haptic_base/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haptic_base::PWMValues16_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haptic_base::PWMValues16_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptic_base::PWMValues16_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptic_base::PWMValues16_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptic_base::PWMValues16_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptic_base::PWMValues16_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haptic_base::PWMValues16_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21fd2457fe29da615fb66ec76d0b748c";
  }

  static const char* value(const ::haptic_base::PWMValues16_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21fd2457fe29da61ULL;
  static const uint64_t static_value2 = 0x5fb66ec76d0b748cULL;
};

template<class ContainerAllocator>
struct DataType< ::haptic_base::PWMValues16_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haptic_base/PWMValues16";
  }

  static const char* value(const ::haptic_base::PWMValues16_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haptic_base::PWMValues16_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[16] pwm_values\n\
";
  }

  static const char* value(const ::haptic_base::PWMValues16_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haptic_base::PWMValues16_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWMValues16_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haptic_base::PWMValues16_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haptic_base::PWMValues16_<ContainerAllocator>& v)
  {
    s << indent << "pwm_values[]" << std::endl;
    for (size_t i = 0; i < v.pwm_values.size(); ++i)
    {
      s << indent << "  pwm_values[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.pwm_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPTIC_BASE_MESSAGE_PWMVALUES16_H
