// Generated by gencpp from file haptic_golf/LSM9DS_raw.msg
// DO NOT EDIT!


#ifndef HAPTIC_GOLF_MESSAGE_LSM9DS_RAW_H
#define HAPTIC_GOLF_MESSAGE_LSM9DS_RAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace haptic_golf
{
template <class ContainerAllocator>
struct LSM9DS_raw_
{
  typedef LSM9DS_raw_<ContainerAllocator> Type;

  LSM9DS_raw_()
    : header()
    , accelData()
    , magData()
    , gyroData()
    , orientation()  {
      accelData.assign(0.0);

      magData.assign(0.0);

      gyroData.assign(0.0);

      orientation.assign(0.0);
  }
  LSM9DS_raw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , accelData()
    , magData()
    , gyroData()
    , orientation()  {
  (void)_alloc;
      accelData.assign(0.0);

      magData.assign(0.0);

      gyroData.assign(0.0);

      orientation.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _accelData_type;
  _accelData_type accelData;

   typedef boost::array<float, 3>  _magData_type;
  _magData_type magData;

   typedef boost::array<float, 3>  _gyroData_type;
  _gyroData_type gyroData;

   typedef boost::array<float, 4>  _orientation_type;
  _orientation_type orientation;




  typedef boost::shared_ptr< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> const> ConstPtr;

}; // struct LSM9DS_raw_

typedef ::haptic_golf::LSM9DS_raw_<std::allocator<void> > LSM9DS_raw;

typedef boost::shared_ptr< ::haptic_golf::LSM9DS_raw > LSM9DS_rawPtr;
typedef boost::shared_ptr< ::haptic_golf::LSM9DS_raw const> LSM9DS_rawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::haptic_golf::LSM9DS_raw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace haptic_golf

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'haptic_golf': ['/home/raven/ros_ws/src/haptic_golf/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8bdef954b5990975e7acefa1ca27db1";
  }

  static const char* value(const ::haptic_golf::LSM9DS_raw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8bdef954b599097ULL;
  static const uint64_t static_value2 = 0x5e7acefa1ca27db1ULL;
};

template<class ContainerAllocator>
struct DataType< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "haptic_golf/LSM9DS_raw";
  }

  static const char* value(const ::haptic_golf::LSM9DS_raw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32[3] accelData\n\
float32[3] magData\n\
float32[3] gyroData\n\
float32[4] orientation\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::haptic_golf::LSM9DS_raw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.accelData);
      stream.next(m.magData);
      stream.next(m.gyroData);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LSM9DS_raw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::haptic_golf::LSM9DS_raw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::haptic_golf::LSM9DS_raw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "accelData[]" << std::endl;
    for (size_t i = 0; i < v.accelData.size(); ++i)
    {
      s << indent << "  accelData[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.accelData[i]);
    }
    s << indent << "magData[]" << std::endl;
    for (size_t i = 0; i < v.magData.size(); ++i)
    {
      s << indent << "  magData[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.magData[i]);
    }
    s << indent << "gyroData[]" << std::endl;
    for (size_t i = 0; i < v.gyroData.size(); ++i)
    {
      s << indent << "  gyroData[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyroData[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HAPTIC_GOLF_MESSAGE_LSM9DS_RAW_H
