# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from haptic_base/DSValues.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class DSValues(genpy.Message):
  _md5sum = "6adcc043e40096395efe95f2a02fadce"
  _type = "haptic_base/DSValues"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """duration ds_dur
int16 ds_angle
int16 ds_entry_angle
time ds_start_time

"""
  __slots__ = ['ds_dur','ds_angle','ds_entry_angle','ds_start_time']
  _slot_types = ['duration','int16','int16','time']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ds_dur,ds_angle,ds_entry_angle,ds_start_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DSValues, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ds_dur is None:
        self.ds_dur = genpy.Duration()
      if self.ds_angle is None:
        self.ds_angle = 0
      if self.ds_entry_angle is None:
        self.ds_entry_angle = 0
      if self.ds_start_time is None:
        self.ds_start_time = genpy.Time()
    else:
      self.ds_dur = genpy.Duration()
      self.ds_angle = 0
      self.ds_entry_angle = 0
      self.ds_start_time = genpy.Time()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2i2h2I().pack(_x.ds_dur.secs, _x.ds_dur.nsecs, _x.ds_angle, _x.ds_entry_angle, _x.ds_start_time.secs, _x.ds_start_time.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ds_dur is None:
        self.ds_dur = genpy.Duration()
      if self.ds_start_time is None:
        self.ds_start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.ds_dur.secs, _x.ds_dur.nsecs, _x.ds_angle, _x.ds_entry_angle, _x.ds_start_time.secs, _x.ds_start_time.nsecs,) = _get_struct_2i2h2I().unpack(str[start:end])
      self.ds_dur.canon()
      self.ds_start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2i2h2I().pack(_x.ds_dur.secs, _x.ds_dur.nsecs, _x.ds_angle, _x.ds_entry_angle, _x.ds_start_time.secs, _x.ds_start_time.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ds_dur is None:
        self.ds_dur = genpy.Duration()
      if self.ds_start_time is None:
        self.ds_start_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 20
      (_x.ds_dur.secs, _x.ds_dur.nsecs, _x.ds_angle, _x.ds_entry_angle, _x.ds_start_time.secs, _x.ds_start_time.nsecs,) = _get_struct_2i2h2I().unpack(str[start:end])
      self.ds_dur.canon()
      self.ds_start_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i2h2I = None
def _get_struct_2i2h2I():
    global _struct_2i2h2I
    if _struct_2i2h2I is None:
        _struct_2i2h2I = struct.Struct("<2i2h2I")
    return _struct_2i2h2I
