// Generated by gencpp from file ros_start/Rt2Sensor.msg
// DO NOT EDIT!


#ifndef ROS_START_MESSAGE_RT2SENSOR_H
#define ROS_START_MESSAGE_RT2SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Accel.h>
#include <geometry_msgs/Twist.h>

namespace ros_start
{
template <class ContainerAllocator>
struct Rt2Sensor_
{
  typedef Rt2Sensor_<ContainerAllocator> Type;

  Rt2Sensor_()
    : accel()
    , velocity()  {
    }
  Rt2Sensor_(const ContainerAllocator& _alloc)
    : accel(_alloc)
    , velocity(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Accel_<ContainerAllocator>  _accel_type;
  _accel_type accel;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;




  typedef boost::shared_ptr< ::ros_start::Rt2Sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_start::Rt2Sensor_<ContainerAllocator> const> ConstPtr;

}; // struct Rt2Sensor_

typedef ::ros_start::Rt2Sensor_<std::allocator<void> > Rt2Sensor;

typedef boost::shared_ptr< ::ros_start::Rt2Sensor > Rt2SensorPtr;
typedef boost::shared_ptr< ::ros_start::Rt2Sensor const> Rt2SensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_start::Rt2Sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_start::Rt2Sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ros_start

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ros_start': ['/home/raven/ros_ws/src/rosrt_rt2/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ros_start::Rt2Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_start::Rt2Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_start::Rt2Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_start::Rt2Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_start::Rt2Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_start::Rt2Sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_start::Rt2Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2491e1f415bd2e4546b770ef2b167077";
  }

  static const char* value(const ::ros_start::Rt2Sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2491e1f415bd2e45ULL;
  static const uint64_t static_value2 = 0x46b770ef2b167077ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_start::Rt2Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_start/Rt2Sensor";
  }

  static const char* value(const ::ros_start::Rt2Sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_start::Rt2Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Accel accel\n\
geometry_msgs/Twist velocity\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Accel\n\
# This expresses acceleration in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
";
  }

  static const char* value(const ::ros_start::Rt2Sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_start::Rt2Sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accel);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Rt2Sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_start::Rt2Sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_start::Rt2Sensor_<ContainerAllocator>& v)
  {
    s << indent << "accel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Accel_<ContainerAllocator> >::stream(s, indent + "  ", v.accel);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_START_MESSAGE_RT2SENSOR_H
